### ISSUE TITLE
Missing template diagram/erd_template.gommd in v0.2.0

### ISSUE THREAD

**Issue by SahAssar** [KarnerTh/mermerd#10]
Thanks so much for the quick fix in #8, when trying it out on the schema that produced that issue for me I ran into another issue though. Turning on the debug flag (thanks for that too) I got this output:

```
.  ..___.__ .  ..___.__ .__ 
|\/|[__ [__)|\/|[__ [__)|  \
|  |[___|  \|  |[___|  \|__/ (0.2.0)

Create MermaidJs diagrams from your database

INFO[0000] Got tables                                    count=1
INFO[0000] Got columns and constraints constraints       columns=5 constraints=0
ERRO[0000] Could not load template file | open diagram/erd_template.gommd: no such file or directory 
```

If I manually download that file and place it in the path it works, but I'm guessing that it was meant to be bundled into the binary.

**Comment by KarnerTh** [comment]
Thanks for pointing out - totally missed that one due to local testing.

Created a patch version [0.2.1](https://github.com/KarnerTh/mermerd/releases/tag/v0.2.1) that fixes the issue - feel free to reopen the ticket if it not works as expected.
