### ISSUE TITLE
MSSQL Support

### ISSUE THREAD

**Issue by kennethcurrie** [KarnerTh/mermerd#13]
trying to connect to an MSSQL DB results in a connection error

**Comment by KarnerTh** [comment]
Currently only PostgreSQL and MySQL are supported, but I will look into the support for MSSQL 👍

**Comment by KarnerTh** [comment]
@kennethcurrie Sorry for the late reply, been quite busy lately.
MSSQL support was added in the [0.3.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.3.0) release.

Example connection string would be something like `sqlserver://user:password@localhost:1433?database=yourDb`

If you find any issues, please do not hesitate to create another ticket :)
