### ISSUE TITLE
Cool idea of a tool!

### ISSUE THREAD

**Issue by lillheaton** [KarnerTh/mermerd#2]
Hey @KarnerTh!

This looks really cool and a promising idea. My immediate reflection is 

- Would it be possible to opt in on all tables?
- Not force input interaction and relay on config/inputs
- Make it more accessible to use in a CI / CD pipeline. 
    - Maybe host it on docker?

Eager to see more of this. Good work so far!

**Comment by KarnerTh** [comment]
Thanks for the input, glad to hear the tool is finding its use.
For the first two points - I can definitely provide these features (and plan to do so in the near future).

Regarding the usage in a CI/CD pipeline, shouldn't it work to just grab the binary from the GitHub release page (or put a copy of the binary in your repository)?
How would the process look like if it was provided via docker? Pull the image and execute the command inside the container?

**Comment by KarnerTh** [comment]
Hey @lillheaton 

I released a new version of mermerd ([v0.0.3](https://github.com/KarnerTh/mermerd/releases/tag/v0.0.3)).

* You can now opt in for all tables via the `--useAllTables` flag
* You can provide a run config to run mermerd e.g. in your CI/CD pipeline (documented [here](https://github.com/KarnerTh/mermerd#use-a-predefined-run-configuration-eg-for-cicd))
  * I also added the feature to define a list of tables you want to generate an ERD for, if all tables are just too much information or you want to split different parts of your database in different ERD files

Everything should be documented in the readme, but please let me know if something is missing or unclear.

Regarding the accessibility for CI/CD pipelines: if using the binary (like described [here](https://github.com/KarnerTh/mermerd/issues/2#issuecomment-1059159468)) is not sufficient, please open another issue with more details.
