### ISSUE TITLE
feature request: support for wildcard schema/useAllSchemas flag/config

### ISSUE THREAD

**Issue by kennethcurrie** [KarnerTh/mermerd#23]
One of the reasons we're using a tool to map out oru DC for our documentation is that our DB isn't... cleanly seperated. Because of that individually mapping schemas means the bridges get missed, is there a way to add either a wildcard option in the checma selection/config and/or add a useAllSchemas flag/config to allow mapping between schemas?

**Comment by KarnerTh** [comment]
Would it be ok if the schema selection would be the same as for the tables?
- multiselection via cli
- list of schemas in (run-)config
- a `--useAllSchemas` flag

it would not be a wildcard option, but rather a multiselect

**Comment by kennethcurrie** [comment]
Sounds perfect!

⁣Get BlueMail for Android ​

**Comment by KarnerTh** [comment]
I finally found the time - support for multiple schemas is now added in version 0.5.0

you can use the `--useAllSchemas` flag, the interactive cli or a list of schemas in your (run-)config. Examples are in the readme
