### ISSUE TITLE
Feature: Prefix table names with schema names

### ISSUE THREAD

**Issue by Hirvox** [KarnerTh/mermerd#30]
I have an SQL Server database with multiple schemas. Some of the table names in these schemas overlap, which causes mermerd to generate two entities with identical names. When rendered, mermaid will combine these entities into a single entity.

Ideally, these table names would be prefixed with the schema name in the generated Mermaid graph, optionally with a configurable separator like an underscore.

For example, for a database with these schemas and tables:
```TSQL
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE SCHEMA Foo
GO

CREATE TABLE [Foo].[Bar](
	[Baz] [nchar](10) NULL,
	[Qux] [nchar](10) NULL
) ON [PRIMARY]
GO

CREATE SCHEMA Quux
GO

CREATE TABLE [Quux].[Bar](
	[Grault] [nchar](10) NULL,
	[Garply] [nchar](10) NULL
) ON [PRIMARY]
GO
```
mermerd will generate this graph:
```mermaid
erDiagram
    Bar {
        nchar Baz 
        nchar Qux 
    }

    Bar {
        nchar Grault 
        nchar Garply 
    }

```
This would be more accurate:
```mermaid
erDiagram
    Foo_Bar {
        nchar Baz 
        nchar Qux 
    }

    Quux_Bar {
        nchar Grault 
        nchar Garply 
    }

```

**Comment by KarnerTh** [comment]
Thanks for bringing that up and creating the detailed feature request - I really appreciate it!

That makes total sense - I will be releasing that feature shortly

**Comment by KarnerTh** [comment]
This feature is available in Version [0.6.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.6.0)

The schema prefix is disabled by default, but can be enabled by the config `showSchemaPrefix`. For the separator `.` is used by default, but can be overwritten by `schemaPrefixSeparator`. 

All the configs can either be set via the command line, run config or the global mermerd config (see readme for details)

Your described example can e.g. be achieved by `mermerd --showSchemaPrefix --schemaPrefixSeparator="_"`

If anything does not work as expected, please let me know

**Comment by Hirvox** [comment]
Thanks, the entities are now generated correctly with schema prefixes. But `showSchemaPrefix` doesn't seem to apply to entity relationships.

A slightly more complicated example:
```TSQL
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE SCHEMA Foo
GO

CREATE TABLE [Foo].[Bar](
	[Baz] [nchar](10) NULL,
	[Qux] [nchar](10) NULL,
	[Id] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Bar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [Foo].[Fred](
	[BarId] [uniqueidentifier] NOT NULL,
	[Waldo] [nchar](10) NULL
) ON [PRIMARY]
GO

ALTER TABLE [Foo].[Fred]  WITH CHECK ADD  CONSTRAINT [FK_Fred_Bar] FOREIGN KEY([BarId])
REFERENCES [Foo].[Bar] ([Id])
GO

ALTER TABLE [Foo].[Fred] CHECK CONSTRAINT [FK_Fred_Bar]
GO


```
will generate this graph:
```mermaid
erDiagram
    "Foo.Bar" {
        nchar Baz 
        nchar Qux 
        uniqueidentifier Id PK
    }

    "Foo.Fred" {
        uniqueidentifier BarId FK
        nchar Waldo 
    }

    Fred }o--|| Bar : "BarId"
```
But it should have generated:
```mermaid
erDiagram
    "Foo.Bar" {
        nchar Baz 
        nchar Qux 
        uniqueidentifier Id PK
    }

    "Foo.Fred" {
        uniqueidentifier BarId FK
        nchar Waldo 
    }

    "Foo.Fred" }o--|| "Foo.Bar" : "BarId"
```

**Comment by KarnerTh** [comment]
Thanks for the quick feedback - this was poorly tested on my side.

The Version [0.6.1](https://github.com/KarnerTh/mermerd/releases/tag/v0.6.1) fixes that issue.

**Comment by Hirvox** [comment]
0.6.1 works fine, thanks.
