### ISSUE TITLE
Sort table names in mermaid file

### ISSUE THREAD

**Issue by austin-artificial** [KarnerTh/mermerd#34]
Sometimes the ordering of the tables changes in the mermaid file after a schema changes (at least with postgres). This can make diffs on that file a bit noisy.

I propose that the tables are alphabetically sorted. This could be done here:
https://github.com/KarnerTh/mermerd/blob/d02edee5be037d52709a41ba5006103ef5bbf119/analyzer/analyzer.go#L58-L61
so that it isn't up to the individual database analyzers to worry about this. 

If this isn't desirable default behaviour, maybe we could put it behind a `--sortTables` flag.

I'd be happy to have a go at implementing this if the approach is agreed upon.

**Comment by KarnerTh** [comment]
The change is available in version [0.8.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.8.0)
