### ISSUE TITLE
ERRO[0002] Getting constraints failed

### ISSUE THREAD

**Issue by lnschroeder** [KarnerTh/mermerd#36]
When using this minimal schema:
```sql
CREATE TABLE
    main (
        id text PRIMARY KEY
    );

CREATE TABLE
    sub1 (
        id text PRIMARY KEY,
        CONSTRAINT cons_name FOREIGN KEY (id) REFERENCES main (id)
    );

CREATE TABLE
    sub2 (
        id text PRIMARY KEY,
        CONSTRAINT cons_name FOREIGN KEY (id) REFERENCES main (id)
    );
```
I get the following error:
```
Getting columns and constraints
ERRO[0002] Getting constraints failed | 
ERROR: more than one row returned by a subquery used as an expression (SQLSTATE 21000) 
ERRO[0002] 
ERROR: more than one row returned by a subquery used as an expression (SQLSTATE 21000) 
```

The error does **not** occur when:
- the constraint names `cons_name` for the `sub1` and `sub2` are different  **or**
- at least one of the `id`'s of the `sub` tables is not declared as `PRIMARY KEY` (i.e. `sub2 (id text, ...)`)

Tested on version: v0.7.1

**Comment by lnschroeder** [comment]
FYI: I am using Postgres, where the constraint names do not have to unique:

> Because PostgreSQL does not require constraint names to be unique within a schema (but only per-table), it is possible that there is more than one match for a specified constraint name. In this case SET CONSTRAINTS will act on all matches. For a non-schema-qualified name, once a match or matches have been found in some schema in the search path, schemas appearing later in the path are not searched.

https://www.postgresql.org/docs/current/sql-set-constraints.html

**Comment by KarnerTh** [comment]
Thanks for the ticket and the detailed description - I will have a look!
