### ISSUE TITLE
MSSQL with a named instance

### ISSUE THREAD

**Issue by MarkEwer** [KarnerTh/mermerd#38]
I'm trying out this tool to hook it into our documentation system but I ran into a snag. My MSSQL server uses a Named Instance that is not the default. I can't quite figure out how to put that instance name in the connection string?

Is this an unsupported scenario?

**Comment by KarnerTh** [comment]
Sry for the late response

I am not an expert regarding MSSQL, but according to the docs it should work like that `sqlserver://username:password@host/instance?param1=value&param2=value` (Source [here](https://github.com/denisenkom/go-mssqldb#connection-parameters-and-dsn))

Have you tried to add the instance name after the host?

**Comment by KarnerTh** [comment]
Any update on the issue? Does it work now?

**Comment by MarkEwer** [comment]
Not for me.

**Comment by RafBorrelli** [comment]
I managed to get it working. This is the pattern I'm using for Windows Authentication:
`sqlserver://[SERVER NAME]/[INSTANCE NAME]?Database=[DATABASE NAME]&Trusted_Connection=True&TrustServerCertificate=True`

For example, assuming this parameters:
- Server Name = DBServer.local
- Instance Name = INSTANCE_TEST
- Database Name = DB_Test

The connection string will be:
`sqlserver://DBServer.local/INSTANCE_TEST?Database=DB_Test&Trusted_Connection=True&TrustServerCertificate=True`

**Comment by KarnerTh** [comment]
Close this for now - if anyone still has issues feel free to reopen
