### ISSUE TITLE
Sort column names in mermaid file

### ISSUE THREAD

**Issue by aslakhellesoy** [KarnerTh/mermerd#40]
We sometimes get inconsistent column order on different machines. This causes the same diffing problem as outlined in #34.

**Comment by KarnerTh** [comment]
Your fix is available in the new version [0.8.1](https://github.com/KarnerTh/mermerd/releases/tag/v0.8.1)

Thanks again for the contribution!

**Comment by KarnerTh** [comment]
Change is available in version [0.9.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.9.0).

Thanks again!

**Comment by chinchala** [comment]
As I see columns are sorted by alphabetical order. Is there any chance to get columns order as it is in source table.
