### ISSUE TITLE
Add unique constraint to key column

### ISSUE THREAD

**Issue by lnschroeder** [KarnerTh/mermerd#43]
Mermaid supports `UK` (see [here](https://mermaid.js.org/syntax/entityRelationshipDiagram.html#attribute-keys-and-comments)) for the unique constraint. It would be great if mermerd could also show this. 

![image](https://github.com/KarnerTh/mermerd/assets/33390735/9775e3dd-6d49-4951-b421-8271420782d5)

I am happy to make a PR for this.

All feedback is welcome :)

**Comment by KarnerTh** [comment]
Totally agree as well :)

Feel free to create a PR!
