### ISSUE TITLE
Enhancement: Support Relationship Labels

### ISSUE THREAD

**Issue by dangoslen** [KarnerTh/mermerd#48]
Hi! Just discovered MermaidJS and this tool! Really exciting stuff and bridges a gap I've been trying to cover for a while now.

I have a feature request that I'd love to discuss with you a little bit, but would be happy to implement if you agree with the direction.

## Feature Description
Based on the MermaidJS specification for an ER Diagram is that it supports the ability to specify any name for a relationship. Right now, I see that you are using the constraint name as the label (based on configuration). I think it would be useful to allow for specifying these labels via the config `.yaml` file and as a CLI argument

One approach would be to use a list of strings that specify `<first-entity> <second-entity> : <label>` (which is similar to the specification for mermaid, but omits the inner `<relation>` - so it should be simple to parse.

Mermerd also looks to use the constraints as the relationship labels, with the option to omit them. I think that if a relationship label exists in the config, that label _must_ be used regardless of the constraint label being omitted or not.

## Proposed Configuration Details

A `<relationship-label>` is defined as `entity entity : label`

The `label` portion should allow only alpha characters, `-`,  and `_`

### CLI Option
`--labels` or `relationshipLabels`: a string of comma-delimited  `<relationship-label>` values: `<relationship-label>[, <relationship-label>]`

### YAML Option
`labels` or `relationshipLabels`: an array of `<relationship-label>` values

**Comment by KarnerTh** [comment]
@dangoslen Thanks for the feature request!

One case we would need to cover is, that there could be multiple relations between two entities 🤔 So if we just use the entities in the configuration, we can not specify for which relation it should be used. Would it be feasible to use the constraint name in the config?

And I would also prefer `relationshipLabels` as it is more descriptive 

But apart from that, I would appreciate a PR and will happily integrate it into the tool 👌🏼

**Comment by dangoslen** [comment]
Sorry for the late reply!

I'm planning to start working on this in the upcoming week.

I guess that could be possible to your point about multiple relationships between entities, but I've only seen those relationships happening via "through" tables.

Will use `relationshipLabels`.

**Comment by KarnerTh** [comment]
PR is merged back, will release a new version as soon as #53 is finished

**Comment by KarnerTh** [comment]
Now available in version [0.10.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.10.0)
