### ISSUE TITLE
[Feature Request] sqlite3 support

### ISSUE THREAD

**Issue by RivenSkaye** [KarnerTh/mermerd#49]
It'd be amazing if this tool were able to generate diagrams based on either existing sqlite3 databases. Considering the alternative is to make a dump and import it elsewhere, or using other tools like MySQL Workbench to generate the diagrams off the dumps themselves, I think it'd be amazing to integrate diagram generation into CI or some other automation process.

Provided the support for it, an automation runner could also load an SQL dump from an unsupported DB into an in-memory sqlite3 DB (assuming it doesn't use esoteric data types) and generate the diagrams off of that, similar to how [SQLx (the one for Rust)](https://github.com/launchbadge/sqlx) offline mode caches valid prepared statements for compile-time checked queries to ensure valid results.

**Comment by KarnerTh** [comment]
Very busy at the moment, but I'll definitely will look into this 👍🏼 should not be a lot of effort

**Comment by KarnerTh** [comment]
Now available in version [0.10.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.10.0)
