### ISSUE TITLE
Support multiple key constraints on a single attribute

### ISSUE THREAD

**Issue by lnschroeder** [KarnerTh/mermerd#51]
When a column is a primary key and foreign key at the same time, only the `PK` constraint will be shown, even though mermaid supports `PK,FK` inside the constraint column:

```mermaid
erDiagram
    CAR ||--o{ NAMED-DRIVER : allows
    CAR {
        string registrationNumber PK
        string make
        string model
    }
    PERSON ||--o{ NAMED-DRIVER : is
    PERSON {
        string driversLicense PK "The license #"
        string name
    }
    NAMED-DRIVER {
        string carRegistrationNumber PK, FK
        string driverLicence PK, FK
    }
``` 

I will create a PR, as this is a necessary feature to start with the PR for #43.

**Comment by KarnerTh** [comment]
Now available in version [0.10.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.10.0)
