### ISSUE TITLE
Unable to run after installing in a way described in README

### ISSUE THREAD

**Issue by pktiuk** [KarnerTh/mermerd#61]
Hello, I installed this app using instructions in Readme, but I can't run it

```
pkot@comp:~$ go install github.com/KarnerTh/mermerd@latest
go/pkg/mod/modernc.org/libc@v1.49.3/pthread_musl.go:11:2: package slices is not in GOROOT (/usr/lib/go-1.18/src/slices)
pkot@comp:~$ mermerd
mermerd: command not found
```

I am on Ubuntu 22.04

**Comment by KarnerTh** [comment]
Hi @pktiuk 👋🏼 

Your error message shows that you are using go version 1.18, unfortunately the project uses a standard lib that is only available >=1.21. You can either update your local go version to 1.21 or above or download a mermerd binary directly from the [Release Page](https://github.com/KarnerTh/mermerd/releases)

I will add the minimal supported go version in the readme to prevent this in the future

**Comment by pktiuk** [comment]
Maybe an AppImage package would be useful? I would just work on any Linux

**Comment by KarnerTh** [comment]
Added the requirement to the readme. For now I will not add an AppImage.
