### ISSUE TITLE
Add debug mode 

### ISSUE THREAD

**Issue by Ragatzino** [KarnerTh/mermerd#8]
Hello, i was really hyped about your tool for documentation :). 

I just tried it on my DB and it does not want to do the job : 
```
more than one row in subquery
```

And i have no clue about what is the problem.

Maybe a --debug flag could be postponed to understand better why it would not work ?

What do you think ?

**Comment by KarnerTh** [comment]
I will see if I can log some useful debug data in the future, a `--debug` flag seems reasonable.

More important, can you provide the DDL of the tables that caused the problem? If yes I would try to reproduce your error and investigate it

**Comment by KarnerTh** [comment]
Thanks for the reproducible schema - I will investigate the issue

**Comment by KarnerTh** [comment]
I have released a new Version ([0.2.0](https://github.com/KarnerTh/mermerd/releases/tag/v0.2.0)) that fixes the issue (thanks to @SahAssar for providing the schema). I have also added an integration test for that kind of schema.

All changes are documented in the [changelog](https://github.com/KarnerTh/mermerd/blob/master/changelog.md#020---2022-06-01)
